version: '2'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./dockerfiles/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: air -c .air.toml

  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./dockerfiles/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
    ports:
      - "3306:3306"
