name: "CI"
on: ["push", "pull_request"]

jobs:
  lint-staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - uses: dominikh/staticcheck-action@v1.2.0

  formatter-gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - run: go fmt

  module-gomodtidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - run: |
          go mod tidy
          git diff --exit-code

  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - run: |
          go test -v
